name: Build and deploy Datasette site

on:
  workflow_dispatch:   # Manual trigger via GitHub UI only

permissions:
  contents: write
  pages: write      # Needed for GitHub Pages
  id-token: write   # Needed for GitHub Pages

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Install sqlite3
      run: sudo apt-get install sqlite3
    
    - uses: actions/cache@v1
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        pip install yaml-to-sqlite datasette datasette-publish-github
    
    - name: Build database from YAML
      run: |
        yaml-to-sqlite browse.db museums museums.yaml --pk=id
        
        # Add country column
        sqlite-utils add-column browse.db museums country 2>/dev/null || true
        
        # Run country SQL script if it exists
        if [ -f set-country.sql ]; then
          sqlite3 browse.db < set-country.sql
        fi
        
        # Setup full-text search
        sqlite-utils disable-fts browse.db museums 2>/dev/null || true
        sqlite-utils enable-fts browse.db museums name description country osm_city --tokenize porter --create-triggers
    
    - name: Build static Datasette site
      run: |
        datasette package browse.db \
          --metadata metadata.yaml \
          --template-dir=templates \
          --plugins-dir=plugins \
          --static static:static/ \
          --outfile=_site
    
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: '_site'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2